<template>
  <div :class="[bem.root, 'common-iw-s']">
    <el-input-number :class="[bem.control]" v-bind="$attrs" v-on="$listeners"></el-input-number>
  </div>
</template>
<script>
import { createNameSpace } from '@component-gallery/utils/bem/create'

const bem = createNameSpace('base-input-number')
export default {
  name: 'base-input-number',
  // This is a computed property that returns an object with two properties: root and control.
  // The root property is generated by calling the bem.b('') method.
  // The control property is generated by calling the bem.e('control') method.
  computed: {
    bem() {
      return {
        root: bem.b(''),
        control: bem.e('control')
      }
    }
  }
}
</script>
<style lang="scss">
@import '~@component-gallery/theme-chalk/src/base-components/base-form/base-input-number';
</style>
