<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.4.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.chinatower.base</groupId>
    <artifactId>shidi-industry-admin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>shidi-industry-admin</name>
    <description>shidi-industry-admin</description>
    <properties>
        <java.version>1.8</java.version>
        <geotools.version>28.4</geotools.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter -->
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.1.6</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.10</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-openfeign -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.2.4.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-api-analysis</artifactId>
            <version>2.6.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>comp-tech-starter-datasource</artifactId>
                    <groupId>com.chinatower</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>video-api-system</artifactId>
                    <groupId>com.chinatower.platform</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-data-sdk</artifactId>
            <version>2.6.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>comp-tech-starter-datasource</artifactId>
                    <groupId>com.chinatower</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>video-api-system</artifactId>
                    <groupId>com.chinatower.platform</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-api-device</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-api-system</artifactId>
            <version>2.6.1</version>
        </dependency>

        <!--图层管理pom-->
        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-api-gis</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-api-bdm</artifactId>
            <version>2.6.1</version>
        </dependency>

        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-application-forestry-api-emengercy</artifactId>
            <version>2.5.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>comp-tech-starter-datasource</artifactId>
                    <groupId>com.chinatower</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>video-api-system</artifactId>
                    <groupId>com.chinatower.platform</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <artifactId>video-api-system</artifactId>
            <groupId>com.chinatower.platform</groupId>
            <version>2.6.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>comp-tech-starter-datasource</artifactId>
                    <groupId>com.chinatower</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--添加easyexcel依赖-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.2.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--        添加配置文件加密依赖-->
        <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
            <version>3.0.5</version>
        </dependency>
        <dependency>
            <groupId>cn.com.vastdata</groupId>
            <artifactId>vastbase-jdbc</artifactId>
            <version>2.9p</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.3.3</version>
        </dependency>
        <dependency>
            <groupId>com.chinatower.platform</groupId>
            <artifactId>video-api-file</artifactId>
            <version>2.6.1</version>
        </dependency>

        <!-- GeoTools Core -->
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-main</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <!-- GeoTools GeoJSON -->
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-geojson</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <!-- GeoTools Shapefile -->
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-shapefile</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-referencing</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-opengis</artifactId>
            <version>${geotools.version}</version>
        </dependency>
        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-metadata</artifactId>
            <version>${geotools.version}</version> <!-- 与 GeoTools 版本一致 -->
        </dependency>

        <dependency>
            <groupId>systems.uom</groupId>
            <artifactId>systems-common</artifactId>
            <version>2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>tech.units</groupId>
                    <artifactId>indriya</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ejml</groupId>
            <artifactId>ejml-core</artifactId>
            <version>0.41</version> <!-- 或最新版本 -->
        </dependency>
        <dependency>
            <groupId>org.ejml</groupId>
            <artifactId>ejml-ddense</artifactId>
            <version>0.41</version>
        </dependency>

        <dependency>
            <groupId>org.geotools</groupId>
            <artifactId>gt-epsg-hsql</artifactId>
            <version>28.0</version>
        </dependency>

        <dependency>
            <groupId>org.locationtech.jts</groupId>
            <artifactId>jts-core</artifactId>
            <version>1.19.0</version> <!-- 与 GeoTools 28.4 兼容的版本 -->
        </dependency>

        <dependency>
            <groupId>javax.measure</groupId>
            <artifactId>unit-api</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>tech.units</groupId>
            <artifactId>indriya</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <!-- 解决 SI 类的直接依赖 -->
            <groupId>si.uom</groupId>
            <artifactId>si-units</artifactId>
            <version>2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>tech.units</groupId>
                    <artifactId>indriya</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>net.sf.json-lib</groupId>
            <artifactId>json-lib</artifactId>
            <version>2.4</version>
            <classifier>jdk15</classifier>
        </dependency>

        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
